var questions = {
  "general": [
    "Explain the pros and cons for CSS animations versus JavaScript animations.",
    "Describe the difference between progressive enhancement and graceful degradation.",
    "Name two ways to decrease page load time.",
    "Explain what ARIA and screenreaders are.",
  ],
  "HTML":[
    "What does doctype do?",
    "What is the difference between HTML and XHTML?",
    "What are data-attributes used for?",
    "What is the difference between <script>, <script async> and <script defer>?",
    "Why are CSS <link>s stored in the <head> and JS <script>s just before the </body>?",
    "What makes HTML5 different?",
    "How can you highlight text in HTML?",
    "What are optional closing tags? Why would you use them?",
    "What is the difference between span and div?",
    "What is semantic HTML?"
  ],
  "CSS": [
    "What's the different between resetting and normalizing CSS?",
    "What does a z-index do?",
    "Describe BFC (Block Formatting Context) and how it works.",
    "What are CSS sprites?",
    "What are the advantages/disadvantages of using CSS preprocessors?",
    "What does box-sizing: border-box; do?",
    "What does a float do?",
    "How can you clear sides of a floating element?",
    "How can you fix floated points that don't add up to the height of the parent?",
    "Explain the difference between div, p; div p; div > p; div + p; p ~ ul",
  ],
  "JS": [
    "Explain how this works in JavaScript.",
    "How does prototypal inheritance work?",
    "What is a promise?",
    "Explain what a closure is.",
    "What is AJAX? How does it work?",
    "What is JSON? How does it work?",
    "Have you used any JavaScript libraries?",
    "What's the difference between .call and .apply?",
    "Explain what hoisting does.",
    "Describe event bubbling.",
    "What is the difference between an 'attribute' and a 'property'?",
    "What is the difference between == and ===?",
    "Can you name two programming paradigms important for JavaScript app developers?",
    "What is functional programming?",
    "What is the difference between classical inheritance and prototypal inheritance?",
    "What are the pros and cons of functional programming vs object-oriented programming?",
    "When is classical inheritance an appropriate choice?",
    "When is prototypal inheritance an appropriate choice?",
    "What does “favor object composition over class inheritance” mean?",
    "What are two-way data binding and one-way data flow, and how are they different?",
    "What are the pros and cons of monolithic vs microservice architectures?",
    "What is asynchronous programming, and why is it important in JavaScript?",
  ],
  "React": [
    "What is React? How is it different from other frameworks?",
    "What happens during the lifecycle of a React component?",
    "What is JSX?",
    "Tell me about Flux",
    "What are stateless components?",
  ],
  "Network": [
    "List all the HTTP actions you know and explain them.",
    "Explain the following request and response headers: Do Not Track, Cache-Control, Transfer-Encoding, ETag, X-Frame-Options, and the difference between Expires, Dates, Age, and If-Modified.",
  ]
}
