var questions = {
  "general": [
    "Explain the pros and cons for CSS animations versus JavaScript animations.",
    "Describe the difference between progressive enhancement and graceful degradation.",
    "Name two ways to decrease page load time.",
    "Explain what ARIA and screenreaders are.",
  ],
  "Angular": [
    "What should be the maximum number of concurrent 'watches'?",
    "How do you share data between controllers?",
    "What is the difference between ng-show/ng-hide and ng-if directives?",
    "What is a digest cycle in Angular JS?",
    "Where should you implement DOM manipulation in Angular JS?",
    "Is it a good or bad practice to use Angular JS together with jQuery?",
    "How would you specify that a scope variable should have one-time binding only?",
    "What is the difference between one-way binding and two-way binding?",
    "How does $scope.$apply() work?",
    "What directive would you use to hide elements from the HTML DOM by removing them from the DOM and not changing their styling?",
    "What makes angular.copy() method so powerful?",
    "How would you make an Angular service return a promise?",
    "When should you use an attribute versus an element?",
    "How do you reset a $timeout, $interval(), and disable a $watch()?",
    "Explain what is a $scope in Angular JS.",
    "What are Directives?",
    "What is DDO Directive Definition Object?",
    "What is a singleton pattern and where can we find it in Angular JS?",
    "What is an interceptor? How is it used?",
    "How would you programatically change or adapt the template of a directive before it is executed and transformed?",
    "How do you hide an HTML element via a button click in Angular JS?",
    "How do you disable a button depending on a checkbox's state?",
  ],
  "CSS": [
    "What's the different between resetting and normalizing CSS?",
    "What does a z-index do?",
    "Describe BFC (Block Formatting Context) and how it works.",
    "What are CSS sprites?",
    "What are the advantages/disadvantages of using CSS preprocessors?",
    "What does box-sizing: border-box; do?",
    "What does a float do?",
    "How can you clear sides of a floating element?",
    "How can you fix floated points that don't add up to the height of the parent?",
    "Explain the difference between div, p; div p; div > p; div + p; p ~ ul",
    "What are some accessibility concerns in CSS?",
    "What tools do you use for cross-browser testing?",
  ],
  "HTML":[
    "What does doctype do?",
    "What is the difference between HTML and XHTML?",
    "What are data-attributes used for?",
    "What is the difference between <script>, <script async> and <script defer>?",
    "Why are CSS <link>s stored in the <head> and JS <script>s just before the </body>?",
    "What makes HTML5 different?",
    "How can you highlight text in HTML?",
    "What are optional closing tags? Why would you use them?",
    "What is the difference between span and div?",
    "What is semantic HTML?",
    "What is progressive rendering?",
    "Explain standard and quirks mode.",
    "What is an optional tag?",
  ],
  "JS": [
    "Explain how this works in JavaScript.",
    "How does prototypal inheritance work?",
    "What is a promise?",
    "Explain what a closure is.",
    "What is AJAX? How does it work?",
    "What is JSON? How does it work?",
    "Have you used any JavaScript libraries?",
    "What's the difference between .call and .apply?",
    "Explain what hoisting does.",
    "Describe event bubbling.",
    "What is the difference between an 'attribute' and a 'property'?",
    "What is the difference between == and ===?",
    "Can you name two programming paradigms important for JavaScript app developers?",
    "What is functional programming?",
    "What is the difference between classical inheritance and prototypal inheritance?",
    "What are the pros and cons of functional programming vs object-oriented programming?",
    "When is classical inheritance an appropriate choice?",
    "When is prototypal inheritance an appropriate choice?",
    "What does favor object composition over class inheritance mean?",
    "What are two-way data binding and one-way data flow, and how are they different?",
    "What are the pros and cons of monolithic vs microservice architectures?",
    "What is asynchronous programming, and why is it important in JavaScript?",
    "What's the difference between null and undefined?",
    "What are the different ways to get an element from the DOM?",
    "How would you destroy multiple list items with one click handler?",
    "How can you verify whether one element is the child of another?"
  ],
  "JS: Algorithm": [
    "Verify a prime number?",
    "Find all prime factors of a number?",
    "Get nth Fibonacci number?",
    "How would you reverse words in a sentence?",
    "How would you merge two sorted arrays?",
    "How would you remove duplicate members from an array?",
    "How would you find the greatest common divisor of two numbers?",
    "How would you verify a word as palindrome?",
    "Reverse a string in JavaScript.",
    "Find the first non repeating char in a string.",
    "Get two numbers that equal to a given number.",
    "Find the largest sum of any two elements.",
    "Check whether a given string is a substring of a bigger string.",
  ],
  "MySQL": [
    "Using SELECT statement, find the version of the server you are running and print the name of the current database.",
    "Is it possible to implement 'AND' with NOT (!) Operator?",
    "What IFNULL() statement is used for in MySQL?",
    "What is MySQL?",
    "What is BLOB and TEXT in MySQL?",
    "What is a trigger in MySQL?",
  ],
  "Network": [
    "List all the HTTP actions you know and explain them.",
    "Explain the following request and response headers: Do Not Track, Cache-Control, Transfer-Encoding, ETag, X-Frame-Options, and the difference between Expires, Dates, Age, and If-Modified.",
  ],
  "React": [
    "What is React? How is it different from other frameworks?",
    "What happens during the lifecycle of a React component?",
    "What is JSX?",
    "Tell me about Flux",
    "What are stateless components?",
    "Explain the Virtual DOM.",
    "How would you create Higher Order Components (HOCs) in React?",
    "What are pure functional Components?",
  ]
}
